;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-backward-char
        evil-backward-word-begin
        evil-change
        evil-delete
        evil-delete-char
        evil-force-normal-state
        evil-forward-char
        evil-forward-word-end
        evil-next-line
        evil-normal-state
        evil-paste-after
        evil-paste-before
        evil-paste-from-register
        evil-paste-pop-next
        evil-previous-line
        evil-use-register
        helm-M-x
        ))

(setq mc/cmds-to-run-once
      '(
        ))
